[tool.poetry]
name = "lady_claude"
version = "0.1.0"
description = ""
authors = ["UniUrchin <85057870+UniUrchin@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "src"}, {include = "lady_claude", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
boto3 = "^1.34.74"
pynacl = "^1.5.0"
requests = "^2.31.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks]
build = { shell = "poetry export --without-hashes -o src/requirements.txt && sam build" }
deploy = { shell = "sam deploy"}
