version = 0.1
[default.deploy.parameters]
stack_name = "penguinator-app"
s3_bucket = "uniurchin-sam-artifact"
s3_prefix = "penguinator-app"
region = "ap-northeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = false
image_repositories = []
