AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 300
    MemorySize: 128

Resources:
  LadyClaudeApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: lady-claude-api
      OpenApiVersion: 3.0.0
      StageName: v1

  LadyClaudeReplyServiceTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: lady-claude-reply-service-topic

  LadyClaudeApiPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Events:
        LadyClaudeApiEvents:
          Type: Api
          Properties:
            Path: /
            Method: POST
            RestApiId: !Ref LadyClaudeApiGateway
      FunctionName: lady-claude-api-post-function
      Handler: lady_claude.function.api.post.function.handler
      MemorySize: 512
      Role: !GetAtt LadyClaudeFunctionRole.Arn
      Runtime: python3.10

  LadyClaudeWorkerReplyServiceAskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Events:
        LadyClaudeSnsEvents:
          Type: SNS
          Properties:
            FilterPolicy:
              command:
                - ask
            Topic: !Ref LadyClaudeReplyServiceTopic
      FunctionName: lady-claude-worker-reply-service-ask-function
      Handler: lady_claude.function.worker.reply_service.ask.function.handler
      Role: !GetAtt LadyClaudeFunctionRole.Arn
      Runtime: python3.10

  LadyClaudeFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: lady-claude-function-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - bedrock:InvokeModel
                  - sns:Publish
                  - sns:Subscribe
                  - ssm:GetParameter
                Resource: "*"
      RoleName: lady-claude-function-role

  LadyClaudeReplyServiceTopicArnParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: /LADY_CLAUDE/REPLY_SERVICE_TOPIC_ARN
      Type: String
      Value: !Ref LadyClaudeReplyServiceTopic
